esphome:
  name: test
  platform: ESP8266
  board: d1

external_components:
  - source: my_components

logger:
  baud_rate: 115200
  level: DEBUG

display:
  - platform: tm1640
    id: tm1640_display
    clk_pin: D6
    dio_pin: D5
    intensity: 3
    length: 16
    lambda: |-
      it.print("-11.2 34.5  65 17.1");
